version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sitemap
    versions:
    - 6.3.5
    - 6.3.6
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.4.0
  - dependency-name: webpack-dev-middleware
    versions:
    - 4.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: memfs
    versions:
    - 3.2.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
